### ISSUE TITLE
403 response

### ISSUE THREAD

**Issue by sum1els** [joelhi/glucose-viewer-pico#9]
Hi, thanks for creating this !

I am getting a 403 response for the API call, with what looks like a cloudflare page about being blocked. If I do a curl with the same details from a linux host I get a proper response:

Running this from the pico:
Logging in...
Connecting to  https://api.libreview.io/llu/auth/login
Response code:  403
Response: 

b'<!DOCTYPE html>\n\n\n\n <html class="no-js" lang="en-US"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />\n\n<style>body{margin:0;padding:0}</style>\n\n\n\n<script>\n  if (!navigator.cookieEnabled) {\n    window.addEventListener(\'DOMContentLoaded\', function () {\n      var cookieEl = document.getElementById(\'cookie-alert\');\n      cookieEl.style.display = \'block\';\n    })\n  }\n</script>\n\n\n\n</head>\n<body>\n  <div id="cf-wrapper">\n    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n    <div id="cf-error-details" class="cf-error-details-wrapper">\n      <div class="cf-wrapper cf-header cf-error-overview">\n        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>\n        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> libreview.io</h2>\n      </div>\n\n      <div class="cf-section cf-highlight">\n        <div class="cf-wrapper">\n          <div class="cf-screenshot-container cf-screenshot-full">\n            \n              <span class="cf-no-screenshot error"></span>\n            \n          </div>\n        </div>\n      </div>\n\n      <div class="cf-section cf-wrapper">\n        <div class="cf-columns two">\n          <div class="cf-column">\n            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>\n\n            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class="cf-column">\n            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>\n\n            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div>\n\n      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n  <p class="text-13">\n    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8835eb638ed8e1d7</strong></span>\n    <span class="cf-footer-separator sm:hidden">&bull;</span>\n    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">\n      Your IP:\n      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>\n      <span class="hidden" id="cf-footer-ip">X.X.X.X</span>\n      <span class="cf-footer-separator sm:hidden">&bull;</span>\n    </span>\n    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>\n</div>\n\n\n    </div>\n  </div>\n\n  <script>\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n'

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "adapters/libreview_adapter.py", line 33, in login
ValueError: syntax error in JSON

Ever seen that before ?

Thanks

**Comment by sum1els** [comment]
when I run that same, using the requests module on my desktop, the API call works

**Comment by joelhi** [comment]
Hey!

Yes, I started getting this very recently, like the past week or so, which has caused some issues with the project. It had been running smoothly for the past 6 months before. Not sure if they recently added some additional security layer. 🤔 Unfortunately I haven't had the time to figure out what is going on yet.

Interesting that it seems to work in different environments. Looking to find the time to sit down and have a proper look at this, but let me know if you find anything else out in the meantime.

Sorry I couldn't be of more help.

Joel

**Comment by sum1els** [comment]
I have no idea why it's happening, not sure if the requests library in the newer micropython is messing the headers up or something, but using yours as an inspiration, I used circuitpy (adafruit requests library), with the waveshare 2" IPS screen (ST7789 library), which shows the colors very nicely at any angle.

![25baa38a-164b-45fd-83e4-2e0ab98e7951](https://github.com/joelhi/glucose-viewer-pico/assets/36119860/51dc0a02-d162-47fe-bcfe-36c216ff8b65)

**Comment by joelhi** [comment]
Looks really nice!

Interesting, I'll give it a go. As you said, it sounds like there may be something in the `urequests` library that trigger cloudflare. Maybe it will catch up with `circuitpy` as well but let's see.

**Comment by spordiab** [comment]
> sum1els

Oh great work @sum1els, would it be possible to have the code because I use the same hardware and Freestyle libre 2.
I tried the ghitub code but unable to connect with Libreview API.

Thank you so much

**Comment by sum1els** [comment]
@spordiab sure, I have uploaded it here: https://github.com/sum1els/circuitpy-glucose-display

thanks to @joelhi for the inspiration, not sure what is wrong with the urequest library, but circuitpy worked for me, however, not sure if it runs out of memory, since sometimes after a few days. maybe weeks the display just goes blank and I need to restart it. Could be my bad programming ;)

**Comment by spordiab** [comment]
> @spordiab sure, I have uploaded it here: https://github.com/sum1els/circuitpy-glucose-display
> 
> thanks to @joelhi for the inspiration, not sure what is wrong with the urequest library, but circuitpy worked for me, however, not sure if it runs out of memory, since sometimes after a few days. maybe weeks the display just goes blank and I need to restart it. Could be my bad programming ;)

Thank you for your response and your work.

I'll try to install it and get back to you.
